### ISSUE TITLE
Finishing touches for website styling (HTML and CSS)

### ISSUE THREAD

**Issue by JamesTheRev13** [abqsada/stock-blogger-project#38]
Be sure to maintain a style consistent with the rest of the site. Pages such as the About Us, Home Page, and Blog Feed are lacking with content. (**Obviously not including incoming data from backend. That is a whole other To-do Item**)

**Comment by MarkusWard93** [comment]
All pages are done besides Blog Feed. Search box locations for ticker and twitter data will need to be decided.
